name = "CallGraphExtractor"
uuid = "6dcc091f-94ef-4703-832e-d27497e8428f"
authors = ["Alexandre Bergel"]
version = "1.0.0-DEV"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
